apiVersion: v1 
kind: ConfigMap 
metadata:
  name: cart-config
data:
  REDIS_HOST: "redis"

---
apiVersion: v1 
kind: Pod 
metadata:
  name: cart 
  lables:
    tier: middle 
    app: cart 
spec:
 containers:
   - image: devopshandson3/cart:v1
     name: cart 
     ports:
      - containerPort: 8080 


---
apiVersion: v1 
kind: Service 
metadata:
  name: cart-service 
spec:
 selector: 
   tier: middle 
   app: cart 
 ports: 
  - protocol: TCP 
    port: 8080
    targetPort: 8080


