apiVersion: v1 
kind: Pod 
metadata: 
  name: rabbit-mq
  labels: 
    tier: mq-system 
    type: rabbit-mq

spec:
 containers: 
   - image: rabbitmq 
     name: rabbitmq 
     ports:
      - containerPort: 5672
      - containerPort: 15672

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: mq-service 
spec:
 selector: 
  tier: mq-system 
  type: rabbit-mq
 ports:
  - port: 5672 
    name: amqp 
  - port: 15672 
    name: http

 




