apiVersion: v1 
kind: Pod 
metadata:
 name: rs-web
 labels:
   tier: front-end 
   app: web-server
spec:
 containers:
   - image: devopshandson3/rs-web:v1
     name: rs-web 
     imagePullPolicy: Always
     ports:
      - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: web-service 
spec:
 type: LoadBalancer 
 selector:
   tier: front-end 
   app: web-server 
 ports:
   - Protocol: TCP 
     port: 81 
     targetPort: 80