apiVersion: v1 
kind: ConfigMap 
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "cities"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
--- 

apiVersion: v1 
kind: Secret
metadata:
 name: sql-creds 
type: opaque 
data:
 MYSQL_USER: c2hpcHBpbmc=
 MYSQL_PASSWORD: c2VjcmV0

--- 

apiVersion: v1 
kind: Pod 
metadata:
  name: mysql 
  labels:
    tier: sql-db 
    type: mysql 
spec:
 containers: 
   - image: devopshandson3/mysql:v1 
     name: mysql 
     imagePullPolicy: Always
     ports:
      - containerPort: 3306

--- 

apiVersion: v1 
kind: Service 
metadata: 
 name: mysql-service 
spec:
 selector: 
   tier: sql-db 
   type: mysql 
 ports: 
   - protocol: TCP 
     port: 3306
     targetPort: 3306

      

