apiVersion: v1 
kind: Pod 
metadata:
  name: catalogue 
  labels:
   tier: middle-service 
   app: catalogue 
spec:
 containers: 
   - image: devopshandson3/catalogue:v1 
     name: catalogue 
     ports:
      - containerPort: 8080 
--- 

apiVersion: v1 
kind: Service 
metadata:
  name: catalogue-service 
spec:
 selector:
  tier: middle-service 
  app: catalogue 
 ports:
  - protocol: TCP 
    port: 8080 
    targetPort: 8080
   
     