apiVersion: v1 
kind: Pod 
metadata:
  name: mongo 
  labels:
    tier: db 
    app: mongodb
spec:
 containers:
   - image: devopshandson3/mongo:v1
     name: mongo 
     imagePullPolicy: Always 
     ports:
      - containerport: 27017
--- 

apiVersion: v1 
kind: Service 
metadata:
  name: mongo-service 
spec:
selector:
  tier: db 
  app: mongodb 
ports:
 - protocol: TCP 
   port: 27017 
   targetport: 27017
     