apiVersion: v1 
kind: ConfigMap 
metadata:
  name: user-configs
data:
  MONGO_URL: http://mongo-service
--- 
apiVersion: v1 
kind: pod 
metadata:
  name: user 
  labels:
    tier: registration&login
    app: user
spec:
 containers:
   - image: devopshandson3/user:v1
     name: user 
     port: 
      - containerPort: 8080 
---

apiVersion: v1 
kind: Service 
metadata:
  name: user-service 
spec:
 selector:
    tier: registration&login
    app: user
ports:
- protocol: TCP 
  port: 87
  targetPort: 8080
  