apiVersion: v1 
kind: Pod 
metadata:
  name: redis 
  labels:
    tier: cacheing-service 
    app: redis 
spec:
 containers:
   - image: redis 
     name: redis 
     ports: 
       - containerPort: 6379
