apiVersion: v1 
kind: Pod 
metadata:
  name: redis 
  labels:
    tier: cacheing-service 
    app: redis 
spec:
 containers:
   - image: redis 
     name: redis 
     ports: 
       - containerPort: 6379
--- 
apiVersion: v1 
kind: Service 
metadata:
 name: redis-service 
spec:
 selector:
   tier: cacheing-service
   app: redis 
 ports: 
  - protocol: TCP 
    port: 6379
    targetPort: 6379
